//
// Product.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Product: JSONEncodable {
    public var id: Int32?
    public var name: String?
    public var price: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Id"] = self.id?.encodeToJSON()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Price"] = self.price
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
