//
// Product.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Product: JSONEncodable {
    public var id: Int32?
    public var name: String?
    public var price: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Id"] = self.id?.encodeToJSON()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Price"] = self.price
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
