//
// RemoveLoginBindingModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RemoveLoginBindingModel: JSONEncodable {
    public var loginProvider: String?
    public var providerKey: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["LoginProvider"] = self.loginProvider
        nillableDictionary["ProviderKey"] = self.providerKey
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
