//
// UserInfoViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class UserInfoViewModel: JSONEncodable {
    public var email: String?
    public var hasRegistered: Bool?
    public var loginProvider: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Email"] = self.email
        nillableDictionary["HasRegistered"] = self.hasRegistered
        nillableDictionary["LoginProvider"] = self.loginProvider
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
