//
// ChangePasswordBindingModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ChangePasswordBindingModel: JSONEncodable {
    public var oldPassword: String?
    public var newPassword: String?
    public var confirmPassword: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["OldPassword"] = self.oldPassword
        nillableDictionary["NewPassword"] = self.newPassword
        nillableDictionary["ConfirmPassword"] = self.confirmPassword
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
