//
// RegisterBindingModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class RegisterBindingModel: JSONEncodable {
    public var email: String?
    public var password: String?
    public var confirmPassword: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["Email"] = self.email
        nillableDictionary["Password"] = self.password
        nillableDictionary["ConfirmPassword"] = self.confirmPassword
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
