//
// PaymentPrepareAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class PaymentPrepareAPI: APIBase {
    /**

     - parameter productId: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func paymentPrepareGet(productId productId: Int32, completion: @escaping ((_ data: String?,_ error: Error?) -> Void)) {
        paymentPrepareGetWithRequestBuilder(productId: productId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /api/PaymentPrepare
     - examples: [{contentType=application/json, example="aeiou"}, {contentType=application/xml, example=string}]
     - examples: [{contentType=application/json, example="aeiou"}, {contentType=application/xml, example=string}]
     
     - parameter productId: (query)  

     - returns: RequestBuilder<String> 
     */
    open class func paymentPrepareGetWithRequestBuilder(productId productId: Int32) -> RequestBuilder<String> {
        let path = "/api/PaymentPrepare"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [
            "productId": productId.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
