//
// PaymentFinalAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class PaymentFinalAPI: APIBase {
    /**

     - parameter transactionAuth: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func paymentFinalPost(transactionAuth transactionAuth: TransactionAuth, completion: @escaping ((_ error: Error?) -> Void)) {
        paymentFinalPostWithRequestBuilder(transactionAuth: transactionAuth).execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     - POST /api/PaymentFinal
     
     - parameter transactionAuth: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func paymentFinalPostWithRequestBuilder(transactionAuth transactionAuth: TransactionAuth) -> RequestBuilder<Void> {
        let path = "/api/PaymentFinal"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = transactionAuth.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
